version: '3.9'

networks:
  common:
    driver: bridge

services:
  db:
    image: postgres:15.1-alpine
    restart: always
    environment:
      POSTGRES_USER: chatapp
      POSTGRES_PASSWORD: chatapp
      POSTGRES_DB: chatapp
    ports:
      - 25432:5432
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    networks:
      - common
